name: Deploy to server

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest

    env:
      NAME: MiVariableDeEntorno

    steps:
      - name: Hola Mundo
        run: echo "Hola mundo"
      - name: Action
        uses: actions/checkout@v4
        with:
          hola: 12

  second_job:
    runs-on: ubuntu-latest
    needs: first_job
    steps:
      - name: Hola Autor del commit
        run: echo "Hola ${{github.actor}}"
  third_job:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar varaible de entorno
        run: echo "Hola $Name"
